### ISSUE TITLE
「任務」ウィンドウについて

### ISSUE THREAD

**Issue by Starmie121** [gre4bee/ElectronicObserver#116]
更新いつもありがとうございます。
5.1.1の更新について、「任務」サブウィンドウがアップデート前と異なるデザインになります。
具体的には、フォントサイズが大きくなり(メインフォントと一緒？)、右端に不明な空白が存在し、フォントの左に空白ができます。
任務ウィンドウを小さいスペースで表示する際、非常に不便なので以前の表示に戻せないでしょうか？
重要ではないので、忙しければ無視しても構いません。
よろしくお願いします。

**Comment by myangelkamikaze** [comment]
It's not possible to revert to the old display, however we're aware that the new version is not very space efficient and are looking into ways to improve it.
About an hour ago we managed to fix the width a bit.
old:
![image](https://user-images.githubusercontent.com/40002167/153028970-86163686-b619-443a-80ca-f37049cc6281.png)
new:
![image](https://user-images.githubusercontent.com/40002167/153028983-4349035c-6f89-4867-9ccc-5307699af4c6.png)

The empty space on the right side is a placeholder for the scrollbar. This is how the theme we're using is designed, so we can't do much about that sadly.
![image](https://user-images.githubusercontent.com/40002167/153029747-2db299ab-383c-4ab9-a38f-d3e69521bdea.png)

The font size is the same as the old view (main font, yes), but it can give the impression of being bigger because the new view uses more height spacing. We're working on reducing the height too, but this seems to be more difficult than fixing width.

**Comment by Starmie121** [comment]
返信遅れて、すみません。
横幅がコンパクトになるだけでもありがたいです。
開発を続けてくれることに、感謝してもしきれません。
Thank you very much!
