### ISSUE TITLE
Add a difference of HP bar background color in the battle window.

### ISSUE THREAD

**Issue by y-jin-yoshihiko** [gre4bee/ElectronicObserver#127]
I want to request additional on the battle window.

Now, the battle window is not easy to differentiate between an enemy ship with a little HP or 0 HP.
![battlewindow1](https://user-images.githubusercontent.com/92554600/157806609-0642ceed-59d8-49b1-8387-ca36b915d27e.png)

So, I want to change the background color of the sinking enemy's HP.
(The below image is edited with MS Paint.)
![battlewindow2](https://user-images.githubusercontent.com/92554600/157806627-19203778-b620-4ec3-89fc-b9743b61a60a.png)

**Comment by myangelkamikaze** [comment]
What do you think about setting the background color of sunken ships to #404DA6DF (4DA6DF is the color in the sink icon, 40 is transparancy to keep things readable).

note: it would be displayed on sunken enemy ships only, here it's displayed on all of them because I didn't implmenet the logic for it yet

![image](https://user-images.githubusercontent.com/40002167/157861980-602c7478-d0a6-4192-beb1-005b30088be8.png) ![image](https://user-images.githubusercontent.com/40002167/157863353-022854d8-4559-4040-b306-c0ef4e83f768.png)

**Comment by y-jin-yoshihiko** [comment]
I think that the difference between sunk or non-sunk ships is OK. 
So the color choice is up to you.
(My image color is chosen as example of easy difference, so that color is not my request.)
