### ISSUE TITLE
Ship encyclopedia search breaks in a couple of ways when ship name translations are turned on.

### ISSUE THREAD

**Issue by Heinrike** [gre4bee/ElectronicObserver#140]
1) The search bar in the ship encyclopedia hangs for a moment every time a letter is typed or deleted.

2) Aside from simply being slow, the search function behaves strangely when the search is longer than 1 character. Specifically:
-Playable ships have to be searched using the romaji spellings of their names, and the search can't cut off in the middle of a syllable. Exceptions are Z1 and Z3, who may be searched as normal for some reason.
-As far as I can tell, abyssal ships are impossible to search for past the first letter of their name.

This makes searching very counter-intuitive and difficult to use. Some examples:

-Mutsuki appears when searching "m", "mu", "mutu", "mutsu", "mutuki" and "mutsuki", but does not appear when searching "mut", "muts", or "mutsuk"
-Akizuki appears when searching "akiduki" but does not appear when searching "akizuki"
-Dan Yang appears when searching "yukikaze" but not "dan yang"
-Jervis appears when searching "ja" but not "je"
-Janus appears when searching for "je" but not "ja"
-Warspite appears when searching "ulosupaito" or "uxosupaito" but not "warspite"
-In order to find "CA Ne-Class," you have to search for "c" and then manually find it among all the ships whose names start with C.

In contrast, the item encyclopedia search seems to function normally even when translations are turned on.

**Comment by myangelkamikaze** [comment]
1. Looks like this only happens when translated names are used, so I probably know what the problem is
2. The search in ship encyclopedia is doing quite a bit behind the scene to make searching more convenient for Japanese users. The main problem is that it was never adjusted properly to include searching through English names.

When inputting Latin characters, it first tries to convert them to hiragana and then check which ship names start with that character. It's basically trying to imitate an IME.
The reason you're getting usable results with only 1 character is because the hiragana conversion fails, so it gets directly compared.

I think changing the logic to convert everything to Latin characters should get rid of the search problems.

**Comment by myangelkamikaze** [comment]
Adjusted a few things and it should work as expected now. The fix will come in version 5.1.4.
