### ISSUE TITLE
ブラウザ画面の位置が変わる

### ISSUE THREAD

**Issue by KimidoriBoushi** [gre4bee/ElectronicObserver#141]
下の画像のような事になりました。
これは、ブラウザと同じ位置に、グループのタブがあり、そのタブ間を往復させたのみです。

再起動すると治りますが、またタブ移動して戻ってくると同じ状態になります。
ブラウザの更新では治りませんが、画面サイズ変更で元の位置に戻ってきます。

クリック判定はブラウザ側にあり、移動した艦これ画面にはありません。

直前にやった事としては、Win10のアップデートがありました。他は特に無し。

![20220327151109](https://user-images.githubusercontent.com/66873075/160269182-2d7820aa-0bff-4de8-8c02-aaed7efc39e4.jpg)

**Comment by myangelkamikaze** [comment]
Does the browser always get stuck there in that position? It looks like 74EO(七四式) lost control over the browser for some reason.

**Comment by KimidoriBoushi** [comment]
いえ、スクリーンショットにして今気づきましたが、若干左に移動してました（5mmほど）。
そしてブラウザのサイズ変更で適切な位置に帰ってきます。

74EO(七四式) も最新バージョンです。

**Comment by Nobuchina** [comment]
I am also experiencing the exact same issue, after a windows 10 update. This is happening already in the previous version.
From my update history, I suspect to be this one (KB5011543):
https://support.microsoft.com/en-us/topic/march-22-2022-kb5011543-os-builds-19042-1620-19043-1620-and-19044-1620-preview-4fe2d1c0-720f-47fe-9523-75339bc107a1

Just to add on some more observations:
1. This also happens when loading a layout from XML.
2. Resizing 74EO seems to fix the issue temporarily, but will happen again after switching tab like the author described.
Combining 1 and 2, if the current size is different from the size defined in the XML, loading the XML will not cause the issue.
3. The wrongly-positioned browser will still move together if 74EO is dragged around.
4. I have dual screens setup. If half of 74EO is dragged to another screen, the browser will come back as well.

**Comment by KimidoriBoushi** [comment]
私もマルチモニタです。なるほど本当に戻ってきました。

これは次のWindows Updateまで待つのみですかね。
ありがとうございました。

**Comment by myangelkamikaze** [comment]
I updated windows now and I'm getting the same problem, I'll look into it.

**Comment by KimidoriBoushi** [comment]
お待ちしております。
応援しかできませんがよろしくおねがいします。

**Comment by myangelkamikaze** [comment]
Looks like this is a WebView2 bug caused by KB5011543.
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2303

**Comment by KimidoriBoushi** [comment]
この.slnを使うのであろう事はわかるのですが、どう使うんだろうというあたりで止まっております。
……解説願えますでしょうか。

**Comment by KimidoriBoushi** [comment]
[WebViewTest.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8341517/WebViewTest.zip)

これを、どう使うのかな、と。
……コレをブラウザのフォルダと一緒に入れるのかなと思い、治ってないので間違えたのかな、と。

**Comment by myangelkamikaze** [comment]
Ah, no, that's just a sample demonstrating the bug. There's no fix for it yet, but the WebView2 team is aware of it and will try to fix it.

**Comment by KimidoriBoushi** [comment]
そうでしたか、ではお待ちしております。
お手数おかけしました。

**Comment by Nightmare000000** [comment]
[](url
![000](https://user-images.githubusercontent.com/103050701/161774537-9e2551fd-cf49-4f88-a0d2-2a6e60cd1fdf.png)
)
この問題はwindows10におけるKB5011543のパッチを当てることによって発生する。
よって、KB5011543をアンインストールすれば発生しないのだが、それだと非常に煩わしい。

以下のパッチがリリースされたのでテストを行った。
https://docs.microsoft.com/en-us/troubleshoot/windows-client/group-policy/use-group-policy-to-deploy-known-issue-rollback
#141の問題に関してKB5011543を入れたままでロールバックするグループポリシーをインストールする。
メリットはKB5011543をインストールしたままで問題が解決した場合windows側で自動的に修正されるかもしれない。
インストール後、グループポリシーエディタを起動。

グループ ポリシー
[ローカル コンピューター ポリシー]
[コンピューターの構成]
[管理用テンプレート]
[KB5011543 Issue 001 Rollback]
[Windows 10, version 2004, 20H2 and 21H1]
[KB5011543 Issue 001 Rollback]
を選び、未構成から無効に変更、再起動をかけた。

#141の問題が起きない事を確認した。
なお、テスト環境は
windows10 pro 21H2

**Comment by KimidoriBoushi** [comment]
理由はわからないのですが治りました。

先程、理由不明のこのブラウザが関係ないであろうフリーズでPC再起動を余儀なくされ、そして再起動したら治りました。
それまでの再起動では治らなかったのですが……一応報告するだけさせていただきます。

再発したらまた報告に来ます。

**Comment by Nobuchina** [comment]
Fixed for me as well.
Seems related to a recent WebView2 update?

**Comment by myangelkamikaze** [comment]
Hmm, it seems like it was also fixed for some others in the WebView2 repository. It's supposedly a Windows regression, so it would probably be fixed with a Windows update.
I'll keep this issue open until they confirm the fix was rolled out in the WebView2 repository.

**Comment by myangelkamikaze** [comment]
Looks like update KB5012599 fixed this problem.
