### ISSUE TITLE
マウスオンした時のウィンドウが一瞬しか表示されない

### ISSUE THREAD

**Issue by maumk2** [gre4bee/ElectronicObserver#158]
マウスをウインドウの中にある資源などに置くと今日獲得した資源の収支が表示されますが一瞬で消えます
設定方法などありますでしょうか？

**Comment by myangelkamikaze** [comment]
https://github.com/gre4bee/ElectronicObserver/issues/128
It's a WPF bug that happens if your display scaling is more than 100%. It's expected to be fixed by .NET 6.0.5, which should be released in about a month.

The current workaround is to set high DPI scaling override to system.
![image](https://user-images.githubusercontent.com/40002167/164404689-bb3e28d9-fa01-4697-84da-4020c600f042.png)

**Comment by maumk2** [comment]
治りました、ありがとうございます

**Comment by myangelkamikaze** [comment]
.NET Runtime 6.0.5 has been released and fixes this bug. It's suggested you remove this workaround after updating.

Download here: https://dotnet.microsoft.com/ja-jp/download/dotnet/thank-you/runtime-desktop-6.0.5-windows-x64-installer

After you install the runtime and restart, your version dialog should show you're using version 6.0.5 and the tooltips will work normally.
![image](https://user-images.githubusercontent.com/40002167/167995896-8eb4cfc5-9fb7-42ca-944a-3761d5ee8174.png)
