### ISSUE TITLE
必要経験値計算で固まる

### ISSUE THREAD

**Issue by daix2z** [gre4bee/ElectronicObserver#205]
新たに別の不具合が見つかりましたのでご報告いたします。
必要経験値計算の画面で対潜装備全表示にチェックをつけた状態にしてしばらくすると画面が固まり操作できない状態になります。
こちらについて同様の事象が発生するかご確認いただけますでしょうか
よろしくお願いいたします。

Version 5.1.9
対象艦:大和改二重

![image](https://user-images.githubusercontent.com/87525340/178955323-869ebc4a-6c92-4927-aa08-8e4be4fec19b.png)

**Comment by myangelkamikaze** [comment]
Hmm, I tried to do that just now, but it seemed to work normally. Can you open task manager before you click and check if your CPU usage goes high?

That event viewer error is not related to the freeze.

**Comment by daix2z** [comment]
事象発生時にタスクマネージャを確認した際はCPU使用率が上がっていることを確認しております。
他ユーザ数人に確認してもらったのですが起きる人と起きない人がいてその差が何かは掴めていない状況です。

イベントビューアのログは無関係でしたか、失礼しました。

**Comment by myangelkamikaze** [comment]
There are probably some unoptimized calculations going on in that case which could cause older processors to struggle. Does this only happen with 大和改二重 or other ships too?

**Comment by daix2z** [comment]
大和改二重以外では今のところ事象は発生していないです。

・確認済(問題なし)
夕張改二特
日向改二
加賀改二護
タシュケント改
村雨改二

**Comment by myangelkamikaze** [comment]
Ah, one last question, did the freeze happen right after you clicked the checkbox, or when you move your mouse above the equipment cell.

I could reproduce the freeze when hovering the equipment cell, the reason for this being that there are simply a lot of different combinations available.

It depends a bit on your equipment, but in my case I get this. In the highlighted row in the Value column, you can see `{[46, Count = 316]}`. This means that in order to get 46 anti-submarine value, there are 316 possible combinations. Displaying all of those in the tooltip caused the freeze.

![image](https://user-images.githubusercontent.com/40002167/179392468-73691b05-2e66-41d9-ae10-212c4cafd0f4.png)

I fixed this by limiting the number of possible results. It will now display a maximum of 6 different equipment setups for each equipment count at most.

Example:

![image](https://user-images.githubusercontent.com/40002167/179392625-78d817df-4c5f-4b92-9619-103494daf322.png)

**Comment by daix2z** [comment]
確認ありがとうございます。
チェックをつけただけではフリーズせず、カーソルを乗せたタイミングでフリーズしました。

**Comment by myangelkamikaze** [comment]
The fix will be available in the next version.
