### ISSUE TITLE
Expedition ( Battle Type 2 ) Check Support

### ISSUE THREAD

**Issue by y-jin-yoshihiko** [gre4bee/ElectronicObserver#80]
Expedition ( Battle Type 2 ) has been verified to cause no damage when fleet status is 2x the requirement.
I want to check this, so that all fleet statuses that are more than 2x the requirement of the expedition show ◎ instead of ○.

**Comment by myangelkamikaze** [comment]
It seems that damage was observed at 216%, so the currently verified minimum is 217%. We should probably use that value.

https://twitter.com/CC_jabberwock/status/1381532727170637827

**Comment by y-jin-yoshihiko** [comment]
>myangelkamikaze
I see, but for expedition (combat type 2), it seems to be 200% or more, even with damage, less than 小破.

Moreover, Mr. CC said that it is almost impossible to achieve 217% in reality.
https://twitter.com/CC_jabberwock/status/1383687865754783747

If the 217% is to be implemented, I think it would be better to have three levels: ○->●->◎, or users can configure the percentage to be ◎.

**Comment by myangelkamikaze** [comment]
Hmm yeah, reaching 217% might be a problem.
We're currently considering showing ◎ for 217%, but also displaying the % for each required stat.

For example: ○ 火力 (150%), 対空 (220%)

**Comment by y-jin-yoshihiko** [comment]
>displaying the % for each required stat.
That might be a lot of work for your team to implement, but I think it's a very nice idea!

**Comment by myangelkamikaze** [comment]
It looks like this for now:

![image](https://user-images.githubusercontent.com/40002167/143564295-df2bb208-bbeb-4bb1-8478-754f943654d5.png)
![image](https://user-images.githubusercontent.com/40002167/143564309-a10c4fea-00b7-40af-9434-3329e27fe7ff.png)

◎ when all your stats are above 217%, ○ when some are under 217%. Additionally the percentage for each stat is displayed next to the symbol. ★ will be displayed next to stats that are above the 217% threshold. Tooltips were also adjusted to be split by newlines instead of commas for easier reading.
